"""add lines, station complexes, stations and segments

Revision ID: 16840f36f5fa
Revises: 0eed9e8b080c
Create Date: 2026-09-12

The core topology: what lines exist, what stations exist, where they are, and
which stations are adjacent on which line. Interchanges and step-free access
follow in the next revision; this one is usable without them.

Autogenerated, then edited in two places. Both edits are things Alembic gets
wrong rather than preferences:

1. `import geoalchemy2` was missing. Autogenerate emits
   `geoalchemy2.types.Geography(...)` in the column definition but does not
   add the import, so the file raises NameError the moment it is run.

2. The downgrade dropped the tables and left the transport_mode enum type
   behind. Postgres does not remove a type when the table using it goes, so
   `downgrade` followed by `upgrade` failed with "type transport_mode already
   exists". The explicit drop at the end of downgrade fixes it, and the
   reversibility test covers it.

Every constraint here is named by the convention on Base.metadata —
ck_segments_seconds_positive rather than whatever Postgres would have
invented — so a later migration can reference one by a name that is derivable
rather than looked up in psql.
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "16840f36f5fa"
down_revision: str | Sequence[str] | None = "0eed9e8b080c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("tube", "overground", "dlr", "elizabeth", name="transport_mode"),
            nullable=False,
        ),
        sa.Column("colour", sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lines")),
        sa.UniqueConstraint("code", name=op.f("uq_lines_code")),
    )
    op.create_table(
        "station_complexes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tfl_hub_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_station_complexes")),
        sa.UniqueConstraint("tfl_hub_id", name=op.f("uq_station_complexes_tfl_hub_id")),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("naptan_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("complex_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["complex_id"],
            ["station_complexes.id"],
            name=op.f("fk_stations_complex_id_station_complexes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stations")),
        sa.UniqueConstraint("naptan_id", name=op.f("uq_stations_naptan_id")),
    )
    # GiST, not btree. A btree index on a geography column is useless — it can
    # order values but cannot answer "within this distance of that point",
    # which is the only question ever asked of this column.
    op.create_index(
        "ix_stations_location",
        "stations",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("origin_station_id", sa.Integer(), nullable=False),
        sa.Column("destination_station_id", sa.Integer(), nullable=False),
        sa.Column("seconds", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "origin_station_id <> destination_station_id",
            name=op.f("ck_segments_origin_differs_from_destination"),
        ),
        sa.CheckConstraint("seconds > 0", name=op.f("ck_segments_seconds_positive")),
        sa.ForeignKeyConstraint(
            ["destination_station_id"],
            ["stations.id"],
            name=op.f("fk_segments_destination_station_id_stations"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["lines.id"],
            name=op.f("fk_segments_line_id_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["origin_station_id"],
            ["stations.id"],
            name=op.f("fk_segments_origin_station_id_stations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_segments")),
        sa.UniqueConstraint(
            "line_id",
            "origin_station_id",
            "destination_station_id",
            name=op.f("uq_segments_line_id_origin_station_id_destination_station_id"),
        ),
    )
    op.create_index("ix_segments_line_id", "segments", ["line_id"], unique=False)
    op.create_index(
        "ix_segments_origin_station_id", "segments", ["origin_station_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_segments_origin_station_id", table_name="segments")
    op.drop_index("ix_segments_line_id", table_name="segments")
    op.drop_table("segments")
    op.drop_index(
        "ix_stations_location", table_name="stations", postgresql_using="gist"
    )
    op.drop_table("stations")
    op.drop_table("station_complexes")
    op.drop_table("lines")

    # Autogenerate does not emit this. Dropping a table does not drop the enum
    # type it used, so without it the next upgrade fails with
    # "type transport_mode already exists".
    sa.Enum(name="transport_mode").drop(op.get_bind(), checkfirst=False)
