"""add station lines and interchanges

Revision ID: 3138067a609f
Revises: 16840f36f5fa
Create Date: 2026-09-12

The two tables that make multi-criteria routing possible.

station_lines declares a relationship that was in the 2021 data all along but
undeclared: 486 station rows for 346 stations, King's Cross appearing six
times, one row per (station, line) with nothing saying so. Because it was
implicit, "which lines serve this station" was not a query you could write,
and Traversal.Create_graph had to rediscover the grouping by deduplicating
name strings on every single search.

interchanges has no 2021 equivalent whatsoever. Changing line had no
representation - not a missing column, a missing idea - which is why the old
router could neither count changes nor weight them. A row per line pair makes
a change an edge with a cost, which is what the (station, line) node
expansion in the engine will be built on.

Autogenerated and accepted as produced. Unlike the previous revision this one
needed no edits: no geography column, so no missing geoalchemy2 import, and
no new enum type, so nothing left behind on downgrade.

Both step-free flags carry a server_default as well as a Python-side default,
so the guarantee holds for a bulk insert that bypasses the ORM - which is
what a seed script tends to do.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3138067a609f"
down_revision: str | Sequence[str] | None = "16840f36f5fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "interchanges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("from_line_id", sa.Integer(), nullable=False),
        sa.Column("to_line_id", sa.Integer(), nullable=False),
        sa.Column("seconds", sa.Integer(), nullable=False),
        sa.Column(
            "step_free",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_line_id <> to_line_id", name=op.f("ck_interchanges_lines_differ")
        ),
        sa.CheckConstraint(
            "seconds > 0", name=op.f("ck_interchanges_seconds_positive")
        ),
        sa.ForeignKeyConstraint(
            ["from_line_id"],
            ["lines.id"],
            name=op.f("fk_interchanges_from_line_id_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("fk_interchanges_station_id_stations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_line_id"], ["lines.id"], name=op.f("fk_interchanges_to_line_id_lines")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interchanges")),
        sa.UniqueConstraint(
            "station_id",
            "from_line_id",
            "to_line_id",
            name=op.f("uq_interchanges_station_id_from_line_id_to_line_id"),
        ),
    )
    op.create_index(
        "ix_interchanges_station_id", "interchanges", ["station_id"], unique=False
    )
    op.create_table(
        "station_lines",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column(
            "step_free_to_platform",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["lines.id"],
            name=op.f("fk_station_lines_line_id_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("fk_station_lines_station_id_stations"),
            ondelete="CASCADE",
        ),
        # Composite primary key: a station serves a line once or not at all,
        # which removes the need for a separate unique constraint.
        sa.PrimaryKeyConstraint("station_id", "line_id", name=op.f("pk_station_lines")),
    )


def downgrade() -> None:
    op.drop_table("station_lines")
    op.drop_index("ix_interchanges_station_id", table_name="interchanges")
    op.drop_table("interchanges")
