"""document every column with a comment

Revision ID: e8e5d6bb1156
Revises: 3138067a609f
Create Date: 2026-09-13

COMMENT ON COLUMN for all 28 columns, so `\\d+ segments` in psql explains the
schema to whoever is looking at it. The model files carry the reasoning; these
carry the one-line definition, and they travel with the database rather than
with the repository.

No structural change — tables, constraints and indexes are untouched.

Why a separate revision rather than folding the comments into the two
revisions that created these tables: those have already been applied. Editing
an applied migration means the file no longer describes what a database that
already ran it actually did. Additive is the only honest option.

Autogenerated, then edited once: `import geoalchemy2` was missing again, for
stations.location. That is the second time — the defect is noted in the header
of revision 16840f36f5fa and it recurs on every revision touching a geography
column. Alembic emits `geoalchemy2.types.Geography(...)` and never adds the
import, and the failure is a NameError partway through `upgrade()`. Because
Postgres DDL is transactional the partial migration rolls back cleanly, which
is why it presents as "Target database is not up to date" rather than as a
half-migrated schema.
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e8e5d6bb1156"
down_revision: str | Sequence[str] | None = "3138067a609f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "interchanges",
        "id",
        existing_type=sa.INTEGER(),
        comment="Surrogate identifier for this interchange.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "interchanges",
        "station_id",
        existing_type=sa.INTEGER(),
        comment="Station where the change happens.",
        existing_nullable=False,
    )
    op.alter_column(
        "interchanges",
        "from_line_id",
        existing_type=sa.INTEGER(),
        comment="Line being left.",
        existing_nullable=False,
    )
    op.alter_column(
        "interchanges",
        "to_line_id",
        existing_type=sa.INTEGER(),
        comment="Line being joined.",
        existing_nullable=False,
    )
    op.alter_column(
        "interchanges",
        "seconds",
        existing_type=sa.INTEGER(),
        comment="Walk time between platforms, seconds. Must be > 0.",
        existing_nullable=False,
    )
    op.alter_column(
        "interchanges",
        "step_free",
        existing_type=sa.BOOLEAN(),
        comment="Step-free for this change. False when unknown.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "lines",
        "id",
        existing_type=sa.INTEGER(),
        comment="Surrogate identifier for this line.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "lines",
        "code",
        existing_type=sa.VARCHAR(length=64),
        comment="TfL line id, e.g. 'victoria'. Also our stable code.",
        existing_nullable=False,
    )
    op.alter_column(
        "lines",
        "name",
        existing_type=sa.VARCHAR(length=128),
        comment="Display name as TfL gives it, e.g. 'Victoria'.",
        existing_nullable=False,
    )
    op.alter_column(
        "lines",
        "mode",
        existing_type=postgresql.ENUM(
            "tube", "overground", "dlr", "elizabeth", name="transport_mode"
        ),
        comment="Kind of service: tube, overground, dlr or elizabeth.",
        existing_nullable=False,
    )
    op.alter_column(
        "lines",
        "colour",
        existing_type=sa.VARCHAR(length=7),
        comment="Hex from TfL design standards. Not served by the API.",
        existing_nullable=False,
    )
    op.alter_column(
        "segments",
        "id",
        existing_type=sa.INTEGER(),
        comment="Surrogate identifier for this segment.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "segments",
        "line_id",
        existing_type=sa.INTEGER(),
        comment="The line this hop is on. Part of its identity.",
        existing_nullable=False,
    )
    op.alter_column(
        "segments",
        "origin_station_id",
        existing_type=sa.INTEGER(),
        comment="Station this hop departs from.",
        existing_nullable=False,
    )
    op.alter_column(
        "segments",
        "destination_station_id",
        existing_type=sa.INTEGER(),
        comment="Station this hop arrives at.",
        existing_nullable=False,
    )
    op.alter_column(
        "segments",
        "seconds",
        existing_type=sa.INTEGER(),
        comment="Ride time in seconds. Must be > 0.",
        existing_nullable=False,
    )
    op.alter_column(
        "station_complexes",
        "id",
        existing_type=sa.INTEGER(),
        comment="Surrogate identifier for this complex.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "station_complexes",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment="Name of the complex, e.g. 'Bank and Monument'.",
        existing_nullable=False,
    )
    op.alter_column(
        "station_complexes",
        "tfl_hub_id",
        existing_type=sa.VARCHAR(length=64),
        comment="TfL hubNaptanCode, e.g. 'HUBBAN'. Null if no hub.",
        existing_nullable=True,
    )
    op.alter_column(
        "station_lines",
        "station_id",
        existing_type=sa.INTEGER(),
        comment="The station this line calls at.",
        existing_nullable=False,
    )
    op.alter_column(
        "station_lines",
        "line_id",
        existing_type=sa.INTEGER(),
        comment="The line calling at that station.",
        existing_nullable=False,
    )
    op.alter_column(
        "station_lines",
        "step_free_to_platform",
        existing_type=sa.BOOLEAN(),
        comment="Step-free street to platform. False when unknown.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "stations",
        "id",
        existing_type=sa.INTEGER(),
        comment="Surrogate identifier for this station.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "stations",
        "naptan_id",
        existing_type=sa.VARCHAR(length=64),
        comment="NaPTAN code from TfL. The external identity.",
        existing_nullable=False,
    )
    op.alter_column(
        "stations",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment="TfL commonName verbatim. Never corrected here.",
        existing_nullable=False,
    )
    op.alter_column(
        "stations",
        "location",
        existing_type=geoalchemy2.types.Geography(
            geometry_type="POINT",
            srid=4326,
            dimension=2,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        comment="WGS84 point (SRID 4326). GiST indexed.",
        existing_nullable=False,
    )
    op.alter_column(
        "stations",
        "complex_id",
        existing_type=sa.INTEGER(),
        comment="Interchange complex this station belongs to, if any.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stations",
        "complex_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Interchange complex this station belongs to, if any.",
        existing_nullable=True,
    )
    op.alter_column(
        "stations",
        "location",
        existing_type=geoalchemy2.types.Geography(
            geometry_type="POINT",
            srid=4326,
            dimension=2,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        comment=None,
        existing_comment="WGS84 point (SRID 4326). GiST indexed.",
        existing_nullable=False,
    )
    op.alter_column(
        "stations",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="TfL commonName verbatim. Never corrected here.",
        existing_nullable=False,
    )
    op.alter_column(
        "stations",
        "naptan_id",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="NaPTAN code from TfL. The external identity.",
        existing_nullable=False,
    )
    op.alter_column(
        "stations",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Surrogate identifier for this station.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "station_lines",
        "step_free_to_platform",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Step-free street to platform. False when unknown.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "station_lines",
        "line_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="The line calling at that station.",
        existing_nullable=False,
    )
    op.alter_column(
        "station_lines",
        "station_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="The station this line calls at.",
        existing_nullable=False,
    )
    op.alter_column(
        "station_complexes",
        "tfl_hub_id",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="TfL hubNaptanCode, e.g. 'HUBBAN'. Null if no hub.",
        existing_nullable=True,
    )
    op.alter_column(
        "station_complexes",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Name of the complex, e.g. 'Bank and Monument'.",
        existing_nullable=False,
    )
    op.alter_column(
        "station_complexes",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Surrogate identifier for this complex.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "segments",
        "seconds",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Ride time in seconds. Must be > 0.",
        existing_nullable=False,
    )
    op.alter_column(
        "segments",
        "destination_station_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Station this hop arrives at.",
        existing_nullable=False,
    )
    op.alter_column(
        "segments",
        "origin_station_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Station this hop departs from.",
        existing_nullable=False,
    )
    op.alter_column(
        "segments",
        "line_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="The line this hop is on. Part of its identity.",
        existing_nullable=False,
    )
    op.alter_column(
        "segments",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Surrogate identifier for this segment.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "lines",
        "colour",
        existing_type=sa.VARCHAR(length=7),
        comment=None,
        existing_comment="Hex from TfL design standards. Not served by the API.",
        existing_nullable=False,
    )
    op.alter_column(
        "lines",
        "mode",
        existing_type=postgresql.ENUM(
            "tube", "overground", "dlr", "elizabeth", name="transport_mode"
        ),
        comment=None,
        existing_comment="Kind of service: tube, overground, dlr or elizabeth.",
        existing_nullable=False,
    )
    op.alter_column(
        "lines",
        "name",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="Display name as TfL gives it, e.g. 'Victoria'.",
        existing_nullable=False,
    )
    op.alter_column(
        "lines",
        "code",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="TfL line id, e.g. 'victoria'. Also our stable code.",
        existing_nullable=False,
    )
    op.alter_column(
        "lines",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Surrogate identifier for this line.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "interchanges",
        "step_free",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Step-free for this change. False when unknown.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "interchanges",
        "seconds",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Walk time between platforms, seconds. Must be > 0.",
        existing_nullable=False,
    )
    op.alter_column(
        "interchanges",
        "to_line_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Line being joined.",
        existing_nullable=False,
    )
    op.alter_column(
        "interchanges",
        "from_line_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Line being left.",
        existing_nullable=False,
    )
    op.alter_column(
        "interchanges",
        "station_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Station where the change happens.",
        existing_nullable=False,
    )
    op.alter_column(
        "interchanges",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Surrogate identifier for this interchange.",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
